### ISSUE TITLE
Hello ! Having a small issue. 

### ISSUE THREAD

**Issue by Leejit** [Muqsit/XPBottle#1]
/exp       error on getExp on line...83? ... pretty sure. 

Feel free to load any software, Genisys (I use Tesseract) and do /exp and it throws an error.

[EDIT]

Actually.... seems anything to do with getExp() is an issue... nothing seems to work.

**Comment by Muqsit** [comment]
Check out the latest version.

**Comment by Leejit** [comment]
Thanks dude !
